#!/bin/sh

# Simple debian package build script
# Debian package tracker: https://tracker.debian.org/pkg/libzc

set -e

D="debtest"
PN="libzc"
PV="0.4.3"
PF="${PN}-${PV}"
PE="orig.tar.gz"
A="${PN}_${PV}.${PE}"

if [ -d ${D} ]; then
    echo "${D} directory exists, cleaning up..."
    rm -rf ${D} && mkdir ${D}
else
    mkdir ${D}
fi

echo "Generating archive..."
if ! git archive --format=tar.gz --prefix=${PF}/ HEAD > ${D}/${A}; then
    echo >&2 "error generating archive"
    exit 1
fi

echo "Expanding archive..."
cd ${D}
tar xvf ${A}
cd ${PF}
cp -ra ../../debian .

echo "Creating debian package..."
debuild

# Next:
# - dput mentors ${PN}_${PV}-1_amd64.changes
# - Send RFS mail to submit@bugs.debian.org

exit 0
