version: '3'
services:
  gcc:
    # will build libzc with gcc
    build: ./docker/gcc
    volumes:
      - ./:/home/dev/libzc
  clang:
    # will build libzc with clang
    build: ./docker/clang
    volumes:
      - ./:/home/dev/libzc
  debian:
    # will build with debian
    build: ./docker/debian
    volumes:
      - ./:/home/dev/libzc
  deb:
    # will build the deb package
    build: ./docker/deb
    volumes:
      - ./:/home/dev/libzc
  scanbuild:
    # will build with clang and run scan-build
    build: ./docker/scanbuild
    volumes:
      - ./:/home/dev/libzc
  mingw64:
    # will build a windows compatible executable
    build: ./docker/mingw64
    volumes:
      - ./:/home/dev/libzc
  afl:
    # will run afl tests
    build: ./docker/afl
    volumes:
      - ./:/home/dev/libzc
