name: Coverity Scan

'on':
  schedule:
    - cron: "17 5 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
      - name: Install dependencies
        run: |
          sudo ./scripts/install-deps.sh
      - name: autogen
        run: ./autogen.sh
      - name: configure
        run: ./configure
      - uses: vapier/coverity-scan-action@v1
        with:
          email: ${{ secrets.COVERITY_SCAN_EMAIL }}
          project: mferland/libzc
          token: ${{ secrets.COVERITY_SCAN_TOKEN }}
          command: make
